### ISSUE TITLE
Feature Request (Support fan controller with light)

### ISSUE THREAD

**Issue by tyjtyj** [PaulAnnekov/tuyaha#1]
Hi, 

I got this linked to smartlife. It does not appear in home assistant. 

How do I begin to debug. I dont mind sharing the device with you

https://www.aliexpress.com/item/33012267944.html?spm=2114.search0104.3.48.24537c4dq1N0kO&ws_ab_test=searchweb0_0%2Csearchweb201602_9_10065_10068_319_10059_10884_317_10887_10696_321_322_10084_453_10083_454_10103_10618_10307_537_536%2Csearchweb201603_53%2CppcSwitch_0&algo_expid=0da1ac8f-081a-4d6d-b5a2-ce8beddabf06-6&algo_pvid=0da1ac8f-081a-4d6d-b5a2-ce8beddabf06

**Comment by tyjtyj** [comment]
Closing as the issue not related to tuyaha.... tuya does not return this device in the tuya list.

**Comment by AnthonyD42** [comment]
Hello, can you check to see if this device is now on the list?  I have a tuya fan/light controller and it’s using the tuya/smartlife app.
