### ISSUE TITLE
Can this work with Tuya-made devices that use their own third-party server?

### ISSUE THREAD

**Issue by mhirsch** [PaulAnnekov/tuyaha#14]
It looks like the subdomain for the API endpoint is [hardcoded](https://github.com/PaulAnnekov/tuyaha/blob/8c48c10d8d8bda1f996551e16820d6c9cc1ea82f/tuyaha/tuyaapi.py#L53
).

I have an Inkbird device that uses Tuya SmartLife to connect to Google Home Assistant and IFTTT. The Inkbird device has it's own clone of the SmartLife app, and seems to log in to different AWS instance, running a very similar SmartLife API. The instance serves a certificate for `*.tuyaus.com`, but is not at the same IP as resolves from `px1.tuyaus.com`. Would it be possible to modify the app to accept the subdomain as a config option along with the region?

**Comment by PaulAnnekov** [comment]
Are you sure this custom domain accepts the same requests as this lib? Did you try to make a request like this https://github.com/PaulAnnekov/tuyaha/blob/8c48c10d8d8bda1f996551e16820d6c9cc1ea82f/tuyaha/tuyaapi.py#L52?

**Comment by Faboor** [comment]
> Would it be possible to modify the app to accept the subdomain as a config option along with the region?

![received_223073822321242](https://user-images.githubusercontent.com/12911864/80894205-fe8d9800-8cd0-11ea-9d1a-b22d87b06cf4.png)

**Comment by PaulAnnekov** [comment]
Stalled.
