### ISSUE TITLE
Tuya WiFi Smart Socket (Power meter and RGB) not add in HA

### ISSUE THREAD

**Issue by tehnoinstyle** [PaulAnnekov/tuyaha#15]
Hello.

You can add support Tuya Smart Socket (with Power meter and RGB lights), such as:
https://www.aliexpress.com/item/33007079896.html?spm=a2g0s.9042311.0.0.5add33eda0TK8U

This device is excellently added to the Tuya Smart application and works, but not added to HA (latest version). Other devices, such as a dimmer, switch, relay, are added to the HA normally, and work from the HA interface normally.

Really add support for this Smart Socket? Thanks.

```
Это устройство превосходно добавляется в приложение Tuya Smart и работает, но не добавляется в ХА (последняя версия). Другие устройства, такие, как диммер, выключатель, реле добавляются в ХА нормально, и работают из интерфейса ХА нормально.

Реально добавить поддержку этой умной розетки? Спасибо.
```

**Comment by PaulAnnekov** [comment]
1. Copy this script to your PC with Python installed or to https://repl.it/ - https://github.com/PaulAnnekov/tuyaha/blob/master/tools/debug_discovery.py
2. Set/update config inside and run it
3. Check if your devices are listed. If they are not - ask Tuya support
4. Remove the updated script, so your credentials won't leak

**Comment by tehnoinstyle** [comment]
Hello.

> Check if your devices are listed. If they are not - ask Tuya support

I am check, Smart Socket not listed.

**Comment by PaulAnnekov** [comment]
Sorry, then this lib can't handle this device. Ask [Tuya support](mailto:support@tuya.com) to support your device in their `/homeassistant` API.
