### ISSUE TITLE
from in authentication request can't be set in session

### ISSUE THREAD

**Issue by kilakewe** [PaulAnnekov/tuyaha#19]
https://github.com/PaulAnnekov/tuyaha/blob/master/tuyaha/tuyaapi.py#L56

It looks like 'tuya' is hard coded. Should this not be able to be set when calling init and fall back to tuya if not defined?

**Comment by PaulAnnekov** [comment]
Did you try to make a request manually and set `from` to value you need? Did it work?

**Comment by PaulAnnekov** [comment]
No reply, closing as stalled.
