### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by LaQuay** [PaulAnnekov/tuyaha#20]
I want to set a schedule for Switch device, but as far I can see neither here nor in HA is there a function available to do it.

Is there someway to schedule the ON / OFF of a switch?
I could do it and do a PR, but I don't know where to find the API documentation (URL and so on...)

Thanks!

**Comment by PaulAnnekov** [comment]
Just google `home assistant schedule switch`, e.g. https://community.home-assistant.io/t/schedule-switch/61499. It's HA responsibility, not this lib.
