### ISSUE TITLE
Is there any documentation about the Tuya API that this library is using?

### ISSUE THREAD

**Issue by bessarabov** [PaulAnnekov/tuyaha#22]
I have just created a pull request to improve how this library is working with brightness ( https://github.com/PaulAnnekov/tuyaha/pull/21 )

I have spend some time debugging the system and finding out how Tuya API is working.

I've tried to find some kind of documentation for this API, but I can't find any.

As I see from the code this library is using several endpoints:

 * `https://px1.tuyaus.com/homeassistant/auth.do`
 * `https://px1.tuyaus.com//homeassistant/access.do`
 * `https://px1.tuyaus.com//homeassistant/skill`

There is `homeassistant` in the url, so I assume that these endpoints were created especially for this library. At first I thought that this server `px1.tuyaus.com` is just a middleware made by the author of this library to proxy requests to the officcial Tuya API, but whois info does not confirm this.

From what I saw during playing with this API I think that the official TuaySmart app is using some other API (Using this API I wasn't able to set the exact same values of the brightness that I can set in the official app).

So, my question. What is this API and is there any official documentation for it?

**Comment by PaulAnnekov** [comment]
That's what I know:
- There was a guy who was working for Tuya Inc and developed original python library. He also developed integration with HA
- He has left the company https://github.com/home-assistant/home-assistant/issues/19074#issuecomment-471370475 ~1 year ago
- This API is quite unstable and it was broken once https://github.com/PaulAnnekov/tuyaha/issues/3#issuecomment-523656935
- I never see any docs about it, so it's unofficial

**Comment by bessarabov** [comment]
Thank you!
