### ISSUE TITLE
Celing fan and wall ceiling fan controller not loading 

### ISSUE THREAD

**Issue by josemalena** [PaulAnnekov/tuyaha#23]
Hi,

I have two kind of celing fan and wall ceiling fan controller, one is RF and WiFi and is installed along the fan, the other is like a WiFi dimmer and goes in the wall. None of them are loading in Home Assistant. See "Abanico Habitación" and "Abanico Oficina". If I can help, please let me know.

![IMG_48FB8C23DCB5-1](https://user-images.githubusercontent.com/21144435/74940029-3cb03680-53c7-11ea-8d59-1c4919308f8d.jpeg)

**Comment by PaulAnnekov** [comment]
1. Copy this script to your PC with Python installed or to https://repl.it/ - https://github.com/PaulAnnekov/tuyaha/blob/master/tools/debug_discovery.py
2. Set/update config inside and run it
3. Check if your devices are listed. If they are not - ask Tuya support
4. Remove the updated script, so your credentials won't leak

**Comment by josemalena** [comment]
Thanks, the devices aren't listed, will ask Tuya support.
