### ISSUE TITLE
IR Gateway and child devices not loading en HA

### ISSUE THREAD

**Issue by josemalena** [PaulAnnekov/tuyaha#24]
IR Gateway and child devices not loading in HA, maybe I can help debugging your API...

**Comment by PaulAnnekov** [comment]
1. Copy this script to your PC with Python installed or to https://repl.it/ - https://github.com/PaulAnnekov/tuyaha/blob/master/tools/debug_discovery.py
2. Set/update config inside and run it
3. Check if your devices are listed. If they are not - ask Tuya support
4. Remove the updated script, so your credentials won't leak

**Comment by josemalena** [comment]
Thanks, the devices aren't listed, will ask Tuya support.
