### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by codeclinic** [PaulAnnekov/tuyaha#26]
Hi,

Is there any chance you could expand the readme a bit, ideally with some installation / setup instructions?

Thanks.

**Comment by PaulAnnekov** [comment]
Hi. I have [this script](https://github.com/PaulAnnekov/tuyaha/blob/master/tools/debug_discovery.py) which authenticates and launches discovery. It has several comments inside. Will it be enough or you need more in-depth instruction?

**Comment by codeclinic** [comment]
Thanks for that. To be honest I don't know what the process of incorporating this into Home Assistant would be. If you could explain that it'd be a great help.

**Comment by PaulAnnekov** [comment]
It's already used by Home Assistant in tuya component https://github.com/home-assistant/core/blob/8402363568929908efa441e50062f13b513e8845/homeassistant/components/tuya/manifest.json#L5 :smile: .

**Comment by codeclinic** [comment]
Ah! Ok, I didn't realise that.
