### ISSUE TITLE
Vacuum support

### ISSUE THREAD

**Issue by dsolmann** [PaulAnnekov/tuyaha#28]
I've been running Home Assistant for a while, and recently bought a Tuya-enabled vacuum robot. I knew, that there was Tuya integration in Home Assistant, but didn't noticed

**Comment by PaulAnnekov** [comment]
Please, check the instruction on how to check whether your device is supported by tuya API https://github.com/PaulAnnekov/tuyaha#how-to-check-whether-the-api-this-library-using-can-control-your-device.

**Comment by dsolmann** [comment]
Yep, it doesn't show up in the script. Closing issue.
