### ISSUE TITLE
Feature request: Tuya smoke detectors

### ISSUE THREAD

**Issue by HA-TB303** [PaulAnnekov/tuyaha#29]
Hi Any chance we will be seeing the tuya smoke detectors beeing supported by this great addon?

I am up for testing If needed :)

**Comment by PaulAnnekov** [comment]
Please, check the instruction on how to check whether your device is supported by tuya API https://github.com/PaulAnnekov/tuyaha#how-to-check-whether-the-api-this-library-using-can-control-your-device.

**Comment by HA-TB303** [comment]
Hi, thanks for your response.

The devices are indeed not showing up. 
```
Getting devices
Got devices
{   u'header': {   u'code': u'SUCCESS', u'payloadVersion': 1},
    u'payload': {   u'devices': [], u'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!
```
I have asked support to add them. Do you have good experiences with tuya support?

**Comment by PaulAnnekov** [comment]
Ok, closing this issue until Tuya will add support.

> Do you have good experiences with tuya support?

Unfortunately no :disappointed:. But sometimes they answer https://github.com/PaulAnnekov/tuyaha/issues/6#issuecomment-529169022.
