### ISSUE TITLE
Can't get it to work...

### ISSUE THREAD

**Issue by arannothc** [PaulAnnekov/tuyaha#41]
Hey, i recently wanted to take control over my "Horsky WIFI Outlets", so i decided to look around, and quick found that they are tuya-made. The App called to control theese is called eFamilyCloud and its contacting tuyaeu.com... I can only login in this App...
In IFTTT im able to login via the "Smart-Life" Service. Tho the Smart-Life App says "Invalid User/Pass"

`REGION = "eu" # cn, eu, us
COUNTRY_CODE = "49" # Your account country code, e.g., 1 for USA or 86 for China
BIZ_TYPE = "smart_life" # tuya, smart_life, jinvoo_smart
FROM = "tuya" # you likely don't need to touch this`

I tried changing from to smart_life aswell. basicly i tried every combination but neither has worked. 

**And yes im sure my username and pasword are correct**

**Comment by KTibow** [comment]
Try deleting your account and making another account, that worked for me.

**Comment by arannothc** [comment]
i just removed the devices from efamilycloud and added them to smartlife
