### ISSUE TITLE
Supports Lampux?

### ISSUE THREAD

**Issue by halkeye** [PaulAnnekov/tuyaha#42]
I got  https://www.amazon.ca/gp/product/B082PG5JD2/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 because I thought I read that home assistant supported them.

I downloaded the app(https://play.google.com/store/apps/details?id=com.lampux.ledbrighter) they mention, and was able to connect to them and configure them

But when I tried to add it to home assistant I got user denied.

I tried to dig into the app without decompiling it, found a certs.json which mentions a1.tuyacn.com, a1.tuyaus.com, a1.tuyaeu.com and a1.tuyain.com

I tried with postman and the debug script, the normal domain doesn't work. I tried with the a1 urls, and homeassistant urls return 404.

Do you have any suggestions for next steps or should I return these?

**Comment by PaulAnnekov** [comment]
If you see `tuya...com` domains it means these light bulbs are definitely using Tuya. I suggest you to experiment with https://github.com/PaulAnnekov/tuyaha#how-to-check-whether-the-api-this-library-using-can-control-your-device. If it won't help you to get a list with your devices - return them.

**Comment by halkeye** [comment]
Yea that's the debug script I tried. I'll try again tonight just in case there's any delay in syncing or something but doesnt look positive

Thanks
