### ISSUE TITLE
Contacsensors not discovered in HA

### ISSUE THREAD

**Issue by francodutch** [PaulAnnekov/tuyaha#45]
WOuld it be possible to add contact-sensors (for instance, to detect wether a door or window is opened or closed) to the Home Assistant integration?

**Comment by PaulAnnekov** [comment]
You this instruction https://github.com/PaulAnnekov/tuyaha#how-to-check-whether-the-api-this-library-using-can-control-your-device to check whether Tuya API returns these sensors to us.

**Comment by PaulAnnekov** [comment]
No answer.
