### ISSUE TITLE
Support for Tuya Vacuum Cleaner

### ISSUE THREAD

**Issue by Lightningpicture** [PaulAnnekov/tuyaha#46]
Hey, 

nice Plugin. 
Can you add Support for Vacuum Cleaners?

**Comment by marine1988** [comment]
+1

**Comment by PaulAnnekov** [comment]
https://github.com/PaulAnnekov/tuyaha#how-to-check-whether-the-api-this-library-using-can-control-your-device

**Comment by marine1988** [comment]
yes it has supor but how can i configure it?

**Comment by PaulAnnekov** [comment]
Please, show me the output of that script. Don't forget to remove sensitive data.

**Comment by shoarma4life** [comment]
Hello, ive also bought a tuyavacuum and would love to connect it to home assistant. Can you do anythinh with this output?

Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {'devices': [], 'scenes': []}}

**Comment by PaulAnnekov** [comment]
This output means your device is not supported by the API. Nothing to do.
