### ISSUE TITLE
Support for WIFI-IR Universal remote

### ISSUE THREAD

**Issue by tzeming** [PaulAnnekov/tuyaha#47]
Hi,Can you add Support for WIFI-IR Universal remote(Model:TY-IR-01)?
![image](https://user-images.githubusercontent.com/72696058/96172692-5a836a80-0f59-11eb-8758-14c64e9e2e00.png)

**Comment by PaulAnnekov** [comment]
https://github.com/PaulAnnekov/tuyaha#how-to-check-whether-the-api-this-library-using-can-control-your-device

**Comment by PaulAnnekov** [comment]
No answer.
