### ISSUE TITLE
Double temperature from thermostat when external only sensor is used

### ISSUE THREAD

**Issue by KostyaSha** [PaulAnnekov/tuyaha#48]
In home assistant tuya bht-002 wifi version shows 44 Celsius instead 22 when "OU" (external only) sensor is selected.

**Comment by ollo69** [comment]
In TuyaHA a fix for this was already implemented but need additional coding in HA, already in progress with [this PR](https://github.com/home-assistant/core/pull/41375).
So please wait for next HA release.

**Comment by KostyaSha** [comment]
cool, thanks. I saw that every manual mention it, but didn't wound and issues or PRs. Thanks, again!
