### ISSUE TITLE
Please add support for wattmeter

### ISSUE THREAD

**Issue by havrla** [PaulAnnekov/tuyaha#52]
Helooo,
please please add support/ device wattmeter.

I can provide an account with a connected wattmeter to develop the expansion.
Email for Tuya account with wattmeter: havrla@lhotkanet.cz

Thanks thanks thanks...

Havrla

**Comment by PaulAnnekov** [comment]
https://github.com/PaulAnnekov/tuyaha#how-to-check-whether-the-api-this-library-using-can-control-your-device

**Comment by PaulAnnekov** [comment]
Actually, we can't do anything here w/o Tuya support. Closing for better times.
