### ISSUE TITLE
WI-FI Curtain module 

### ISSUE THREAD

**Issue by blaurence** [PaulAnnekov/tuyaha#53]
Hello,

I have a wifi curtain module, using "debug_discovery.py" the device is listed as a "switch" instead of "cover".
`{   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay15327721968035jwx9/15875408093b983969598.jpg',
                                      'id': 'XXXXXXXXXXXXXXXXX',
                                      'name': 'Volet du bureau'}`

I tried customisation: 
`cover:
  - platform: template
    covers:
      right_shutter:
        device_class: curtain
        friendly_name: "testble"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.XXXXXXXXXXXXXXXXX
        close_cover:
          service: switch.turn_off
          data:
            entity_id: switch.XXXXXXXXXXXXXXXXX`

But i don't work.

I have another device ( https://images.tuyaeu.com/smart/icon/ay15327721968035jwx9/1591929607367ee07f6f2.jpg ) and the device is a cover.

Can you confirm it's a tuya issue ? 
Thanks.

**Comment by IMAMBAKS** [comment]
I also have a [curtain switch: currydouble 5th generation][0] (tuya --> smart_life)  which shows up at Home Assistant, but doesn't respond when turning it on/off:

The script shows the following output:
```
{
   "data":{
      "online":True,
      "state":False
   },
   "dev_type":"switch",
   "ha_type":"switch",
   "icon":"https://images.tuyaeu.com/smart/program_category_icon/clkg.png",
   "id":"XXXXXXXXXXXXXXXXXXXX",
   "name":"rolluik"
}
```

![image](https://user-images.githubusercontent.com/5062713/100496126-f3f58d00-3151-11eb-9149-1b0c071c66dc.png)

Its working in the app flawlessly:

![image](https://user-images.githubusercontent.com/5062713/100496168-4f277f80-3152-11eb-854a-ad8c9111a070.png)

[0]: https://www.amazon.co.uk/Generation-Shutter-Currydouble-Controllable-Safety/dp/B08JM3Q6NF

**Comment by PaulAnnekov** [comment]
@blaurence does it work at least as a switch? Does it reacts on turn on/off in HA?

**Comment by PaulAnnekov** [comment]
@IMAMBAKS https://github.com/PaulAnnekov/tuyaha#my-device-is-not-listed-in-tuya-api-response-or-contains-incomplete-state-what-should-i-do

**Comment by blaurence** [comment]
Thank you for your reply.
No, switch does not do anything.
I also write an email to tuya support but nos response.

**Comment by rulez86** [comment]
Hello, any news about that? I have same issue. Device is shown up as a switch, but it's a curtain. No reaction by using the switch in home assistant.

**Comment by PaulAnnekov** [comment]
Actually, we can't do anything here w/o Tuya support. Closing for better times.
