### ISSUE TITLE
BlitzWolf BW-SHP10 - Smart socket

### ISSUE THREAD

**Issue by kodmarcel** [PaulAnnekov/tuyaha#58]
https://m.blitzwolf.com/3680W-16A-WIFI-Smart-Socket-p-453.html

Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1506337792739cXrIR/1582528361df24235ff77.jpg',
                                      'id': '24005020a4cf12d7983a',
                                      'name': 'BW-SHP10 3 - id_2'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1506337792739cXrIR/1582528361df24235ff77.jpg',
                                      'id': '24005020a4cf12d7974b',
                                      'name': 'BW-SHP10 laptop - id_1'}],
                   'scenes': []}}

**Comment by PaulAnnekov** [comment]
Hi. I don't understand your problem. Don't they appear in Home Assistant?

**Comment by kodmarcel** [comment]
Hey there is no problem :)
I just opened an issue to show compatibility as requested in the faq of the project. Or did i misunderstood?

**Comment by PaulAnnekov** [comment]
You did :), but it's ok. If everything is fine, no need to create an issue.
