### ISSUE TITLE
IBS-M1 Support

### ISSUE THREAD

**Issue by mpfurnari** [PaulAnnekov/tuyaha#64]
For anyone looking to integrate temperature sensors from the Ink Bird M1, I've written an email to tuyasmart@tuya.com. I'll update this issue with any response I get. Not an issue for the dev to handle, just documenting here until this is resolved by Tuya one way or another.

```
Hi,

I've added a device IBS-M1. Your app shows the 4 devices, battery, and temperature - though not formatted. 

If possible, would you add this to the tuyapy library and https://px1.tuya{}.com API endpoint.

Thank you!
```

**Comment by PaulAnnekov** [comment]
I don't think it's a good idea to keep this issue open until Tuya will resolve it. I will close it. It will be still searchable, you can track it and reopen when something will change.
