### ISSUE TITLE
Tuya TRV MOES HY368-ZB

### ISSUE THREAD

**Issue by baddy-0** [PaulAnnekov/tuyaha#65]
I take a TRV https://www.moeshouse.com/collections/trv-radiator-valve/products/tuya-zigbee3-0-new-mini-wifi-radiator-actuator-smart-programmable-thermostat-temperature-trv-controller
It appears in home assistant but 
                                                  'max_temper': 700,
                                                  'min_temper': 10,
are wrong and current_temperature and temperature should by divided by 10
Can you help me?

Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/product_icon2/kg_1.png',
                                      'id': '31110200d8f15b08b419',
                                      'name': 'Salone 2'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/product_icon2/kg_1.png',
                                      'id': '31110200d8f15b07871f',
                                      'name': 'Salone 1'},
                                  {   'data': {   'current_temperature': 195,
                                                  'max_temper': 700,
                                                  'min_temper': 10,
                                                  'online': True,
                                                  'temperature': 200},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',
                                      'icon': 'https://images.tuyaeu.com/smart/program_category_icon/wk.png',
                                      'id': 'bfef0c333e09348175a5fo',
                                      'name': 'Termo Studio'}],
                   'scenes': []}}

**Comment by ReneAlabid** [comment]
I have the exact same problem with the heating. Here's my discovery output:

`
  "Data": {
    "header": {
      "code": "SUCCESS",
      "payloadVersion": 1
    },
    "payload": {
      "devices": [
        {
          "data": {
            "current_temperature": 200,
            "max_temper": 700,
            "min_temper": 10,
            "online": true,
            "temperature": 150
          },
          "dev_type": "climate",
          "ha_type": "climate",
          "icon": "https://images.tuyaeu.com/smart/program_category_icon/wk.png",
          "id": "bf71dec55d92c1ac202vpz",
          "name": "Heizung Ankleide "
        },
        {
          "data": {
            "current_temperature": 230,
            "max_temper": 700,
            "min_temper": 10,
            "online": true,
            "temperature": 240
          },
          "dev_type": "climate",
          "ha_type": "climate",
          "icon": "https://images.tuyaeu.com/smart/program_category_icon/wk.png",
          "id": "bf11fb0e1df5afbac9ckuq",
          "name": "Heizung Esszimmer "
        },
        {
          "data": {
            "current_temperature": 295,
            "max_temper": 700,
            "min_temper": 10,
            "online": true,
            "temperature": 255
          },
          "dev_type": "climate",
          "ha_type": "climate",
          "icon": "https://images.tuyaeu.com/smart/program_category_icon/wk.png",
          "id": "bfffb678ee63b929b1bf9g",
          "name": "Heizung Wohnzimmer "
        },
        {
          "data": {
            "current_temperature": 255,
            "max_temper": 700,
            "min_temper": 10,
            "online": true,
            "temperature": 240
          },
          "dev_type": "climate",
          "ha_type": "climate",
          "icon": "https://images.tuyaeu.com/smart/program_category_icon/wk.png",
          "id": "bf59daebabaa234029slzu",
          "name": "Heizung Badezimmer "
        }
    }
}
`

**Comment by ReneAlabid** [comment]
Every time I want to adjust the temperature, the devices become unavailable immediately. Also I cannot turn them to "Automatic", the state is always "Off". But they show proper current temp and target temp (set inside the Tuya App).

**Comment by ReneAlabid** [comment]
And here is also the logs for this error:
<img width="851" alt="Bildschirmfoto 2021-01-02 um 08 59 32" src="https://user-images.githubusercontent.com/23655945/103453424-21e26a00-4cda-11eb-94d7-c4372e708cee.png">

**Comment by ollo69** [comment]
@baddy-0,

the option to divide the reported temperature value is already available in HA Tuya options page.

@ReneAlabid,

this is a know issue, PR #61 is required to be merged to fix this.

**Comment by PaulAnnekov** [comment]
Closing as the fix was merged.
