### ISSUE TITLE
usr/pwd error

### ISSUE THREAD

**Issue by sebastianet** [PaulAnnekov/tuyaha#66]
Hi - I am using your code "https://github.com/PaulAnnekov/tuyaha/blob/master/tools/debug_discovery.py" 
but receive
'Get accesstoken failed. Username or password error!'

I am using the user and the pwd that I use to access 
>>> https://developer.tuya.com/en/
and
>>> https://iot.tuya.com

It looks they are not the same as the usr/pwd required to access the API

My question is : how do I get a user/pwd to access the tuya cloud using python ?

**Comment by sebastianet** [comment]
I got it running . the usr/pwd are from Smart Life configuration, not tuya cloud

**Comment by PaulAnnekov** [comment]
Cool.
