### ISSUE TITLE
Region support for TuyaApi per instances.

### ISSUE THREAD

**Issue by jasimmk** [PaulAnnekov/tuyaha#68]
Currently SESSION is handled as a single global object. This is causes a limitation for using multiple Tuya accounts with different regions. A better approach without breaking existing code is, We should have an option to pass TuyaSession as an optional parameter.

```python
class TuyaApi:

    def __init__(self, tuya_session=None):
        if tuya_session is None:
            self.tuya_session = SESSION
    ...

    def init(self, username, password, countryCode, bizType=""):
        self.tuya_session.username = username
        self.tuya_session.password = password
        self.tuya_session.countryCode = countryCode
        self.tuya_session.bizType = bizType

```

One of the issue places where we could apply this is selecting the region at home assistant tuya integration. Currently tuya integration at [homeassistant](https://github.com/home-assistant/core) fails for Non US region accounts (Eg: If you have an account with countryCode = 971, ideally it should select region as EU instead of US.

**Comment by PaulAnnekov** [comment]
Feel free to create a PR, I will review and approve.

**Comment by ollo69** [comment]
I think that `DEFAULTREGION` should be managed as optional parameter in `init` function, so we will be able to add a config flow parameter in HA integration to solve login issue.
Manage multiple session in HA will be more complex because require a review of all integration to allow multiple instances.

**Comment by PaulAnnekov** [comment]
@jasimmk I've merged a solution for the optional region. Do you agree to close this issue?

**Comment by jasimmk** [comment]
Sounds good. Thanks, yes we can close the issue
