### ISSUE TITLE
Thermostat target temperature factor 10 different from set temperature

### ISSUE THREAD

**Issue by ksya** [PaulAnnekov/tuyaha#70]
There are currently 2 dividers, one for the current temperature, the other for everything else. I think I may have a special case. 

With current temperature divider to 10 and the temperature divider to default: Can set temperature, but reported target temperature (after getting from device) is 10x too high.

With current temperature divider to 10 and the temperature divider to 10: Can NOT set temperature (too high/low), but reported target temperature is OK

So the divider should not be used for the set_temperature, only for the get_temperature..

**Comment by ollo69** [comment]
This is handled by PR #61, waiting to be merged to implement related PR in HA

**Comment by marleyjaffe** [comment]
Looks like this can be resolved now that PR #61 is merged?

**Comment by ollo69** [comment]
I already created [PR](https://github.com/home-assistant/core/pull/45732) in HA, just waiting for review...

**Comment by PaulAnnekov** [comment]
Closing as the fix was merged.
