### ISSUE TITLE
Merkury Light Bulb (White, Dimmable) appearing as Switch in HA

### ISSUE THREAD

**Issue by austin-engle** [PaulAnnekov/tuyaha#71]
```
{
    "data": {
        "online": True,
        "state": True
    },
    "dev_type": "switch",
    "ha_type": "switch",
    "icon": "https: //images.tuyaus.com/smart/icon/ay1542522254804COaau/1594199026ab77cc15a21.png",
    "id": "eb740c4294bb08464bvmel",
    "name": "Bedroom Lamp"
}
```

My Merkury Bulb (a16) is appearing as a switch in HA but appears as a lightbulb in the smart life app. Not sure what other information is needed.

**Comment by PaulAnnekov** [comment]
Looks like Tuya API doesn't support your lamp as a lamp (on/off, dimmer). It supports it only as a switch (on/off). So ask Tuya for support https://github.com/PaulAnnekov/tuyaha#my-device-is-not-listed-in-tuya-api-response-or-contains-incomplete-state-what-should-i-do, as we can't fix it on our side.
