### ISSUE TITLE
Problem integration for this components 

### ISSUE THREAD

**Issue by MayuriXx** [PaulAnnekov/tuyaha#78]
Hello guys,

I want integrate this object : [https://www.lesalexiens.fr/labo-test-alexa/test-plafonnier-lsc-smart-conect-en-blanc-ou-en-couleur/](url)
It's a ceiling light LSC smart connect. I can integrate it in Tuya or Smartlife app but in Home Assistant, when i want integrate it, i doesn't watch it.
[https://www.home-assistant.io/integrations/tuya](url) 
Can you check it ? I have this object too : [url](https://www.action.com/fr-fr/p/dummy-3003046/)

**Comment by MayuriXx** [comment]
`Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {'devices': [], 'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!`

Ok i checked your script and my object is not integrated

**Comment by PaulAnnekov** [comment]
If the device is not listed, I can't help.
