### ISSUE TITLE
Aborted -- Failed to connect - Home Assistant Core 2021.4.6 - Docker

### ISSUE THREAD

**Issue by ray-su** [PaulAnnekov/tuyaha#80]
I just migrated from an older version of Hassio to Home assistant core in docker. 
And I can not connect to Tuya/Smart Life anymore.  

I've tested my account with that python script, all devices are listed. 

I've also tried moving one of my Smart Life device to Tuya, still no luck.

**Comment by PaulAnnekov** [comment]
Ask here https://github.com/home-assistant/core/issues, it's more relevant place to handle your problem.
