### ISSUE TITLE
Recognition of door detectors

### ISSUE THREAD

**Issue by TroisSix** [PaulAnnekov/tuyaha#82]
Hi guys,

You plugin is great, I really enjoy it ;)

I wanted to discover my **door/window detectors**, but it **doesn't appear in the list of devices** (I also tested the debug_discovery script).
Is it a normal behaviour cause it is not recognized by Tuyaha, or should I look elsewhere?

Appreciate your help ;)

Regards,

**Comment by pironic** [comment]
Unfortunately it doesn't look like my door sensors returned from the api... which according to the documentation we should just email tuya and complain. It is out of the control of the developer of this library to fix anything. :-(

https://github.com/PaulAnnekov/tuyaha#my-device-is-not-listed-in-tuya-api-response-or-contains-incomplete-state-what-should-i-do

**Comment by TroisSix** [comment]
You're right.
I already sent them messages, but no response at all...
So I used the plugin Tuya with my Amazon Alexa account, and virtual switches activated when a sensor is on/off.
It works!

**Comment by PaulAnnekov** [comment]
@pironic is right. The API sucks.
