### ISSUE TITLE
issue with home assistante core2021-6.0 version and later

### ISSUE THREAD

**Issue by robi59italy** [PaulAnnekov/tuyaha#87]
going fro 5.5 to 6.0, all my smartplugs teckin SP22 went out of order. they are still in localtuya but I'm missing the energy monitor information, only looking as switch.

The original tuya integration doesn't  support energy monitor with these smartplugs through tuyapi

**Comment by PaulAnnekov** [comment]
I don't understand your problem. It's a repo of `tuyaha` library (not `localtuya`), which is used by Tuya integration of HA.

**Comment by robi59italy** [comment]
> I don't understand your problem. It's a repo of `tuyaha` library (not `localtuya`), which is used by Tuya integration of HA.

I mean.. localtuya doesn't work anymore with 6.0 version and later.

**Comment by PaulAnnekov** [comment]
You've created an issue in the wrong repo. This repo is not related to `tuyaha`.
